[package]
name = "netpod-jlabath-duckdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
bendy = { version = "0.3.3", features = [] }
duckdb = { version = "1.1.1", features = ["bundled"] }
serde_json = "1.0.132"

